#!/usr/bin/env bash
# GISNEXUS — Fix raster layer download: the GeoTIFF re-encode (via the
# `geotiff` npm package) threw "you passed into encodeImage a width of type
# undefined" — the library rejected the metadata shape we guessed at (no
# network access to check its real API against docs). Rather than guess
# again, this drops that dependency entirely and ships the original PNG
# bytes unchanged, plus a standard ESRI world file (.pgw) and .prj
# projection file — both are plain, unchanging static text formats, so
# there's no third-party API left to get wrong.
#
# Deletes apps/web/src/types/geotiff.d.ts (no longer needed) and rewrites
# apps/web/src/lib/downloadLayer.ts and apps/web/package.json (removes the
# geotiff dependency).
#
# Run this from the ROOT of your gisnexus-app repo, in Git Bash:
#   bash deliver-download-fix.sh
set -e

echo "Removing apps/web/src/types/geotiff.d.ts (no longer needed) ..."
rm -f apps/web/src/types/geotiff.d.ts
rmdir apps/web/src/types 2>/dev/null || true

echo "Writing apps/web/package.json ..."
cat > apps/web/package.json <<'EOF'
{
  "name": "@gisnexus/web",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "preview": "vite preview",
    "typecheck": "tsc --noEmit",
    "deploy": "npm run build && wrangler pages deploy dist --project-name=gisnexus-app"
  },
  "dependencies": {
    "maplibre-gl": "^4.5.0",
    "qrcode": "^1.5.4",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^6.25.1"
  },
  "devDependencies": {
    "@types/qrcode": "^1.5.5",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.4",
    "typescript": "^5.5.3",
    "vite": "^6.0.0",
    "wrangler": "^4.0.0"
  }
}
EOF

echo "Writing apps/web/src/lib/downloadLayer.ts ..."
cat > apps/web/src/lib/downloadLayer.ts <<'EOF'
import { GeoFeatureCollection, LayerDto } from "../api/client";

// Triggers a browser download of an in-memory Blob — shared by the vector
// (GeoJSON) and raster (PNG + world file) download paths below.
function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Give the browser a moment to start the download before freeing the URL.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function safeFilename(name: string) {
  const cleaned = name.replace(/[^a-z0-9\-_. ]/gi, "_").trim();
  return cleaned || "layer";
}

// Vector layers (uploads, buffer/intersect results, Contours, Watershed, ...)
// already have their full feature set loaded client-side in featuresByLayer
// (see MapEditorPage's loadMap, which fetches every non-raster layer's
// features up front) — no server round-trip needed here, just package what's
// already in memory as a standalone .geojson file.
export function downloadVectorLayer(layer: LayerDto, features: GeoFeatureCollection) {
  const blob = new Blob([JSON.stringify(features, null, 2)], { type: "application/geo+json" });
  downloadBlob(`${safeFilename(layer.name)}.geojson`, blob);
}

// Raster layers produced by the terrain tools (Hillshade/Slope/Aspect) are
// stored as a single georeferenced PNG — a data: URL already sitting in
// layer.service.url, with the four corner coordinates in
// layer.service.coordinates (see colorizeSequential/colorizeAspect and
// imageLayerService() in apps/api/src/lib/terrain.ts).
//
// First cut of this shipped a GeoTIFF re-encode via the `geotiff` npm
// package, but its writeArrayBuffer() rejected the metadata shape we
// guessed at ("you passed into encodeImage a width of type undefined") —
// we had no way to check its real API without network access to inspect
// the package, and guessing again risks the same thing. This version drops
// that dependency entirely and instead ships the ORIGINAL PNG bytes
// unchanged, alongside a standard ESRI "world file" (.pgw) and a .prj
// projection file — both are plain static text in a well-documented,
// unchanging format (no library, no binary encoding), so there's nothing
// left to get wrong about a third-party API. Most GIS tools (QGIS, ArcGIS)
// auto-detect a same-named .pgw next to an image and position it correctly
// with no manual georeferencing step; the .prj tells them the coordinates
// are plain lat/lon (WGS84) rather than requiring the user to assign a CRS
// by hand.
//
// This triggers three separate downloads in quick succession — most
// browsers show a one-time "this site wants to download multiple files"
// prompt the first time; click Allow and future downloads from this app
// won't ask again.
//
// Tile-service raster layers (XYZ/WMS/WMTS basemap layers, added via "Add
// data" rather than generated by a terrain tool) are NOT covered — they're
// a live service, not a single fixed image, so there's nothing to export.
const WGS84_PRJ =
  'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]';

export async function downloadRasterLayer(layer: LayerDto) {
  const service = layer.service;
  if (!service || service.type !== "image" || !service.url || !service.coordinates || service.coordinates.length < 4) {
    throw new Error("This layer isn't a downloadable image (it's a live tile service, not a single georeferenced raster).");
  }

  // Only need pixel dimensions here (for the world file's pixel size) — the
  // PNG itself ships as-is, no canvas re-encode, so nothing here can alter
  // or corrupt the original image data.
  const img = new Image();
  img.src = service.url;
  await new Promise<void>((resolve, reject) => {
    img.onload = () => resolve();
    img.onerror = () => reject(new Error("Couldn't decode this layer's image data."));
  });
  const width = img.naturalWidth;
  const height = img.naturalHeight;
  if (!width || !height) throw new Error("This layer's image appears to be empty.");

  const pngResponse = await fetch(service.url);
  const pngBlob = await pngResponse.blob();

  // coordinates is [[west,north],[east,north],[east,south],[west,south]] —
  // see imageLayerService() in apps/api/src/lib/terrain.ts.
  const [west, north] = service.coordinates[0];
  const [east] = service.coordinates[1];
  const [, south] = service.coordinates[2];
  const pixelSizeX = (east - west) / width;
  const pixelSizeY = (north - south) / height;

  // ESRI world file: 6 lines, one number each — x pixel size, rotation (0),
  // rotation (0), negative y pixel size, x-coord of the first pixel's
  // center, y-coord of the first pixel's center. Standard, unchanging
  // format — see https://en.wikipedia.org/wiki/World_file.
  const worldFile =
    [
      pixelSizeX.toFixed(10),
      "0",
      "0",
      (-pixelSizeY).toFixed(10),
      (west + pixelSizeX / 2).toFixed(10),
      (north - pixelSizeY / 2).toFixed(10),
    ].join("\n") + "\n";

  const base = safeFilename(layer.name);
  downloadBlob(`${base}.png`, pngBlob);
  downloadBlob(`${base}.pgw`, new Blob([worldFile], { type: "text/plain" }));
  downloadBlob(`${base}.prj`, new Blob([WGS84_PRJ], { type: "text/plain" }));
}
EOF

echo ""
echo "Done writing files. Now review, build, and push:"
echo ""
echo "  git status"
echo "  git diff --stat"
echo "  npm run build --workspace=apps/web"
echo "  git add -A"
echo "  git commit -m \"Fix raster layer download: PNG + world file instead of GeoTIFF re-encode\""
echo "  git push"