import { writeArrayBuffer } from "geotiff";
import { GeoFeatureCollection, LayerDto } from "../api/client";

// Triggers a browser download of an in-memory Blob — shared by both the
// vector (GeoJSON) and raster (GeoTIFF) download paths below.
function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Give the browser a moment to start the download before freeing the URL.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function safeFilename(name: string) {
  const cleaned = name.replace(/[^a-z0-9\-_. ]/gi, "_").trim();
  return cleaned || "layer";
}

// Vector layers (uploads, buffer/intersect results, Contours, Watershed, ...)
// already have their full feature set loaded client-side in featuresByLayer
// (see MapEditorPage's loadMap, which fetches every non-raster layer's
// features up front) — no server round-trip needed here, just package what's
// already in memory as a standalone .geojson file.
export function downloadVectorLayer(layer: LayerDto, features: GeoFeatureCollection) {
  const blob = new Blob([JSON.stringify(features, null, 2)], { type: "application/geo+json" });
  downloadBlob(`${safeFilename(layer.name)}.geojson`, blob);
}

// Raster layers produced by the terrain tools (Hillshade/Slope/Aspect) are
// stored as a single georeferenced PNG — a data: URL already sitting in
// layer.service.url, with the four corner coordinates in
// layer.service.coordinates (see colorizeSequential/colorizeAspect and
// imageLayerService() in apps/api/src/lib/terrain.ts). To hand the user
// something a GIS tool can position correctly with no separate "bounds"
// file, this decodes that PNG via <canvas> and re-encodes it as a GeoTIFF
// with the same bounds embedded, entirely in the browser — no backend
// changes, no server-side image library, no Docker/binary dependency.
//
// NOTE: this is the least battle-tested part of this feature. We could not
// verify the exact runtime shape `geotiff`'s writeArrayBuffer expects (see
// types/geotiff.d.ts) without network access to inspect the package, so
// this is a best-effort implementation based on the documented GeoTIFF/TIFF
// tag names. If a downloaded .tif won't open, or opens with the wrong
// position/CRS, in QGIS or another GIS tool, that's the first place to look.
// Tile-service raster layers (XYZ/WMS/WMTS basemap layers, added via "Add
// data" rather than generated by a terrain tool) are NOT covered — they're
// a live service, not a single fixed image, so there's nothing to export.
export async function downloadRasterLayer(layer: LayerDto) {
  const service = layer.service;
  if (!service || service.type !== "image" || !service.url || !service.coordinates || service.coordinates.length < 4) {
    throw new Error("This layer isn't a downloadable image (it's a live tile service, not a single georeferenced raster).");
  }

  const img = new Image();
  img.src = service.url;
  await new Promise<void>((resolve, reject) => {
    img.onload = () => resolve();
    img.onerror = () => reject(new Error("Couldn't decode this layer's image data."));
  });

  const canvas = document.createElement("canvas");
  canvas.width = img.naturalWidth;
  canvas.height = img.naturalHeight;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("This browser doesn't support the canvas APIs needed to export this layer.");
  ctx.drawImage(img, 0, 0);

  const { data, width, height } = ctx.getImageData(0, 0, canvas.width, canvas.height);
  if (!width || !height) throw new Error("This layer's image appears to be empty.");

  // De-interleave RGBA -> four separate band arrays. geotiff's reader
  // returns rasters this way (one typed array per band), so its writer is
  // expected to accept the same shape symmetrically.
  const pixelCount = width * height;
  const r = new Uint8Array(pixelCount);
  const g = new Uint8Array(pixelCount);
  const b = new Uint8Array(pixelCount);
  const a = new Uint8Array(pixelCount);
  for (let i = 0; i < pixelCount; i++) {
    r[i] = data[i * 4];
    g[i] = data[i * 4 + 1];
    b[i] = data[i * 4 + 2];
    a[i] = data[i * 4 + 3];
  }

  // coordinates is [[west,north],[east,north],[east,south],[west,south]] —
  // see imageLayerService() in apps/api/src/lib/terrain.ts. NoData pixels
  // (areas the DEM didn't cover) come through with alpha = 0 in this 4th
  // band, same convention the app already uses to render them transparent
  // on the map — if a GIS tool doesn't auto-treat band 4 as a mask/alpha
  // channel, that's a one-time "treat band 4 as alpha" setting to apply.
  const [west, north] = service.coordinates[0];
  const [east] = service.coordinates[1];
  const [, south] = service.coordinates[2];

  const arrayBuffer = await writeArrayBuffer([r, g, b, a], {
    height,
    width,
    ModelPixelScale: [(east - west) / width, (north - south) / height, 0],
    ModelTiepoint: [0, 0, 0, west, north, 0],
    GTModelTypeGeoKey: 2, // Geographic (lat/lon), not a projected CRS
    GTRasterTypeGeoKey: 1, // RasterPixelIsArea
    GeographicTypeGeoKey: 4326, // WGS84 — matches the DEM source, see fetchDem() in terrain.ts
  });

  downloadBlob(`${safeFilename(layer.name)}.tif`, new Blob([arrayBuffer], { type: "image/tiff" }));
}
